### DISCUSSION TITLE
AI on the Edge in the Homeassistant Energy Dashboard

### DISCUSSION THREAD

**Discussion by zumheulen** [jomjol/AI-on-the-edge-device#1342] [Show and tell]
AI on the Edge in the Homeassistant Energy Dashboard
Hello, it took me a long time to get the AI-on-the-Edge in Homeassistant into the Energy Dashboard.

Here are my tips:
1.) In Al on the Edge at MQTT:
- URL mqtt://192.168.1.65:1883 (The IP of your broker e.g. Homeassistant)
- Maintopic: homeassistant/counter/watermeter(as an example)
- clientID: watermeter
- User: MQTT_user (As specified in the MQTT broker)
- Password: (Your password from the MQTT broker)
- Enable MQTT retain flag: true
2.) In Homeassistant in mqtt.yaml:
```
sensor:
- name: "watermeter"
  device_class: "water"
  state_topic: "homeassistant/counter/watermeter/value"
  icon: "mdi:water"
  state_class: "total_increasing"
  unique_id: "mqtt_watermeter_vg_value"
  unit_of_measurement: "m³"
```

to save. --> Developer tools --> Check configuration
If everything is ok, restart and then the water meter should be available for selection in Settings --> Dashboards --> Energy for water!
Hope it helps some ;-)

**Comment by caco3** [comment]
In the next release (and current rolling) we added Homeassistant Discovery.
That makes it even easier, see https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistant

**Reply by maiaz** [reply]
yeah, i confirm. in rolling you just enable HA discovery in settings, and next few minutes everything is picked up automatically by HA.
https://i.imgur.com/OvXSZZq.png

**Comment by busaku** [comment]
Anyone here, that can share a current rolling? Iam to stupid :(

Or: When is next release? ;)

**Reply by caco3** [reply]
The next release hopefully comes end of next week.

Until then you can test the latest rolling:  https://github.com/jomjol/AI-on-the-edge-device/actions?query=branch%3Arolling

**Reply by busaku** [reply]
Thanks :)

**Comment by enjoy-development** [comment]
Hello
my GasMeter AI-on-the-Edge in Homeassistant works fine , but i can't bring it into the Energy Dashboard. :-(
The read from Power Device (NORAX3D) by Tasmota infrared read device

I see the electric device information for all values ​​in my own dashboards,, including energydashboard.
The gasmeter Infos works also well with all values in my own Dashboards , 
but in the energy dashboard is at the dropdown for gas sensor nothing to find :-(
"Keine passenden Statistiken gefunden" = No matching statistics found
Definition in YAML is : 
![image](https://user-images.githubusercontent.com/81940770/203855350-50cdd044-f06d-4d09-9655-4e713d58208b.png)


What is wrong ? 
Can anybody help ?

Regards Oliver

**Reply by caco3** [reply]
Did you try it with the new Discovery Mode (part of rolling)?

Looking on Homeassistant, it seems to generate following config (I did not test if this can be directly copied to the yml file):
```
mqtt:
  unique_id: gaszaehler-value
  object_id: gaszaehler_value
  name: Value
  icon: mdi:gauge
  state_topic: gaszaehler/main/value
  unit_of_measurement: m³
  device_class: gas
  state_class: total_increasing
```
