### DISCUSSION TITLE
Verständnisfrage zur Ersteinrichtung in Home-Assistant

### DISCUSSION THREAD

**Discussion by frittes** [jomjol/AI-on-the-edge-device#2248] [Q&A]
Hallo zusammen,

bin heute mal wieder das Thema Wasserzähler angegangen. Einrichtung des ESP32 war problemlos.

Werte werden per MQTT an HA übertragen. Ich habe nun zum Sammeln der Verbräuche und der Anzeige im Energy Dashboard ein utility_meter angelegt.

Nun zur Verständnisfrage: Der Zählerwert (in meinem Fall 28,nochwas m3) wurde bei HA restart direkt in das utility_meter eingetragen. Ist das so richtig? In dem Fall habe ich heute dann 28000l Wasser verbraucht. Oder habe ich irgendwo einen Fehler gemacht?

utility_meter:

```
water_yearly:
  source: sensor.wasserzaehler_value
  cycle: yearly
water_monthly:
  source: sensor.wasserzaehler_value
  cycle: monthly
water_daily:
  source: sensor.wasserzaehler_value
  cycle: daily
```

  customize_glob:

```
    sensor.water_*:
      last_reset: '1970-01-01T00:00:00+00:00'
      device_class: water
      state_class: total_increasing
      unit_of_measurement: "m³"
      icon: mdi:water
```

Danke vorab!
