### DISCUSSION TITLE
RAW Werte und Werte stimmen nicht überein - Digitaler Wasserzähler

### DISCUSSION THREAD

**Discussion by Henry-Sir** [jomjol/AI-on-the-edge-device#2500] [Q&A]
### The Problem
Hallo, 

vor ca. 2 Wochen wurde unser analoger Wasserzähler gegen einen Digitalen Wasserzähler (Diehl Hydrus) getauscht.
Die Ablesung funktioniert soweit auch, nur nach einiger Zeit laufen die Werte von RAW und Value auseinander. Heißt, er erkennt die richtigen Werte aber es werden nicht die richtigen Werte gesetzt.

Muss in den Einstellungen etwas verändert werden?
Und welche Model zu Erkennung ist das richtige, leider werden nicht alle Model in der Doku beschrieben?

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/75314095/aa89bfc8-2aa6-4ff5-a419-1d52bfbc4808)

### Version
Release: v15.2.4 (Commit: cbd14a2)

### Logfile 

[1d10h50m20s] 2023-06-28T06:15:20	<INF>	[MAINCTRL] Round #210 started
[1d10h51m07s] 2023-06-28T06:16:07	<INF>	[POSTPROC] main: Raw: 7.770, Value: 7.770, Status: no error
[1d10h51m07s] 2023-06-28T06:16:07	<INF>	[MAINCTRL] Round #210 completed (47 seconds)
[1d11h00m20s] 2023-06-28T06:25:20	<INF>	[MAINCTRL] Round #211 started
[1d11h00m46s] 2023-06-28T06:25:46	<INF>	[SNTP] Time is synced with NTP Server pool.ntp.org: 2023-06-28 06:25:46
[1d11h01m07s] 2023-06-28T06:26:07	<INF>	[POSTPROC] main: **Raw: 7.780, Value: 7.770,** Status: no error
[1d11h01m07s] 2023-06-28T06:26:07	<INF>	[MAINCTRL] Round #211 completed (47 seconds)
[1d11h10m20s] 2023-06-28T06:35:20	<INF>	[MAINCTRL] Round #212 started
[1d11h11m07s] 2023-06-28T06:36:07	<INF>	[POSTPROC] main: Raw: 7.803, Value: 7.773, Status: no error
[1d11h11m07s] 2023-06-28T06:36:07	<INF>	[MAINCTRL] Round #212 completed (47 seconds)
[1d11h20m20s] 2023-06-28T06:45:20	<INF>	[MAINCTRL] Round #213 started
[1d11h21m07s] 2023-06-28T06:46:07	<INF>	[POSTPROC] main: Raw: 7.804, Value: 7.774, Status: no error
[1d11h21m07s] 2023-06-28T06:46:07	<INF>	[MAINCTRL] Round #213 completed (47 seconds)
[1d11h30m20s] 2023-06-28T06:55:20	<INF>	[MAINCTRL] Round #214 started
[1d11h31m07s] 2023-06-28T06:56:07	<INF>	[POSTPROC] main: Raw: 7.842, Value: 7.842, Status: no error
[1d11h31m07s] 2023-06-28T06:56:07	<INF>	[MAINCTRL] Round #214 completed (47 seconds)

[1d12h11m07s] 2023-06-28T07:36:07	<INF>	[POSTPROC] main: Raw: 7.848, Value: 7.848, Status: no error
[1d12h11m07s] 2023-06-28T07:36:07	<INF>	[MAINCTRL] Round #218 completed (47 seconds)
[1d12h20m20s] 2023-06-28T07:45:20	<INF>	[MAINCTRL] Round #219 started
[1d12h21m07s] 2023-06-28T07:46:07	<INF>	[POSTPROC] main: **Raw: 7.842, Value: 7.852,** Status: no error
[1d12h21m07s] 2023-06-28T07:46:07	<INF>	[MAINCTRL] Round #219 completed (47 seconds)
[1d12h30m20s] 2023-06-28T07:55:20	<INF>	[MAINCTRL] Round #220 started
[1d12h31m07s] 2023-06-28T07:56:07	<INF>	[POSTPROC] main: **Raw: 7.848, Value: 7.858,** Status: no error
[1d12h31m07s] 2023-06-28T07:56:07	<INF>	[MAINCTRL] Round #220 completed (47 seconds)
[1d12h40m20s] 2023-06-28T08:05:20	<INF>	[MAINCTRL] Round #221 started
[1d12h41m07s] 2023-06-28T08:06:07	<INF>	[POSTPROC] main: **Raw: 7.848, Value: 7.858,** Status: no error
[1d12h41m07s] 2023-06-28T08:06:07	<INF>	[MAINCTRL] Round #221 completed (47 seconds)

[1d15h01m07s] 2023-06-28T10:26:07	<INF>	[POSTPROC] main: Raw: 7.858, Value: 7.968, Status: no error
[1d15h01m07s] 2023-06-28T10:26:07	<INF>	[MAINCTRL] Round #235 completed (47 seconds)
[1d15h10m20s] 2023-06-28T10:35:20	<INF>	[MAINCTRL] Round #236 started
[1d15h11m07s] 2023-06-28T10:36:07	<ERR>	[POSTPROC] main: Raw: 7.852, Value: , Status: Rate too high - Read: 8.852 - Pre: 7.968 - Rate: 0.884
[1d15h11m07s] 2023-06-28T10:36:07	<INF>	[MAINCTRL] Round #236 completed (47 seconds)
[1d15h20m20s] 2023-06-28T10:45:20	<INF>	[MAINCTRL] Round #237 started
[1d15h21m07s] 2023-06-28T10:46:07	<INF>	[POSTPROC] main: Raw: 7.858, Value: 7.968, Status: no error
[1d15h21m07s] 2023-06-28T10:46:07	<INF>	[MAINCTRL] Round #237 completed (47 seconds)

[3d00h00m53s] 2023-06-29T19:25:51	<INF>	[SNTP] Time is synced with NTP Server pool.ntp.org: 2023-06-29 19:25:51
[3d00h01m10s] 2023-06-29T19:26:07	<INF>	[POSTPROC] main: **Raw: 8.255, Value: 8.355**, Status: no error
[3d00h01m10s] 2023-06-29T19:26:07	<INF>	[MAINCTRL] Round #433 completed (47 seconds)
[3d00h10m23s] 2023-06-29T19:35:20	<INF>	[MAINCTRL] Round #434 started
[3d00h11m10s] 2023-06-29T19:36:07	<INF>	[POSTPROC] main: **Raw: 8.397, Value: 8.357**, Status: no error
[3d00h11m10s] 2023-06-29T19:36:07	<INF>	[MAINCTRL] Round #434 completed (47 seconds)
[3d00h20m23s] 2023-06-29T19:45:20	<INF>	[MAINCTRL] Round #435 started
[3d00h21m10s] 2023-06-29T19:46:07	<INF>	[POSTPROC] main: Raw: 8.573, Value: 8.373, Status: no error
[3d00h21m10s] 2023-06-29T19:46:07	<INF>	[MAINCTRL] Round #435 completed (47 seconds)
[3d00h30m23s] 2023-06-29T19:55:20	<INF>	[MAINCTRL] Round #436 started
[3d00h31m10s] 2023-06-29T19:56:07	<INF>	[POSTPROC] main: Raw: 8.690, Value: 8.390, Status: no error
[3d00h31m10s] 2023-06-29T19:56:07	<INF>	[MAINCTRL] Round #436 completed (47 seconds)
[3d00h40m23s] 2023-06-29T20:05:20	<INF>	[MAINCTRL] Round #437 started
[3d00h41m10s] 2023-06-29T20:06:07	<INF>	[POSTPROC] main: Raw: 8.704, Value: 8.394, Status: no error
[3d00h41m10s] 2023-06-29T20:06:07	<INF>	[MAINCTRL] Round #437 completed (47 seconds)
[3d00h50m23s] 2023-06-29T20:15:20	<INF>	[MAINCTRL] Round #438 started
[3d00h51m10s] 2023-06-29T20:16:07	<INF>	[POSTPROC] main: Raw: 8.874, Value: 8.394, Status: no error
[3d00h51m10s] 2023-06-29T20:16:07	<INF>	[MAINCTRL] Round #438 completed (47 seconds)
[3d01h00m23s] 2023-06-29T20:25:20	<INF>	[MAINCTRL] Round #439 started
[3d01h00m53s] 2023-06-29T20:25:51	<INF>	[SNTP] Time is synced with NTP Server pool.ntp.org: 2023-06-29 20:25:51
[3d01h01m10s] 2023-06-29T20:26:07	<ERR>	[POSTPROC] main: Raw: 9.041, Value: , Status: Rate too high - Read: 9.041 - Pre: 8.394 - Rate: 0.647
[3d01h01m10s] 2023-06-29T20:26:07	<INF>	[MAINCTRL] Round #439 completed (47 seconds)

[3d12h00m54s] 2023-06-30T07:25:51 <INF> [SNTP] Time is synced with NTP Server pool.ntp.org: 2023-06-30 07:25:51
[3d12h01m11s] 2023-06-30T07:26:07 <INF> [POSTPROC] main: Raw: 9.418, Value: 8.428, Status: no error
[3d12h01m11s] 2023-06-30T07:26:08 <INF> [MAINCTRL] Round #505 completed (47 seconds)
[3d12h10m24s] 2023-06-30T07:35:20 <INF> [MAINCTRL] Round #506 started
[3d12h11m10s] 2023-06-30T07:36:07 <INF> [POSTPROC] main: Raw: 9.434, Value: 8.434, Status: no error
[3d12h11m11s] 2023-06-30T07:36:07 <INF> [MAINCTRL] Round #506 completed (47 seconds)
[3d12h20m24s] 2023-06-30T07:45:21 <INF> [MAINCTRL] Round #507 started
[3d12h21m11s] 2023-06-30T07:46:07 <INF> [POSTPROC] main: Raw: 9.440, Value: 8.440, Status: no error
[3d12h21m11s] 2023-06-30T07:46:08 <INF> [MAINCTRL] Round #507 completed (47 seconds)

### Config 
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/75314095/b876d10c-3d1f-4263-9e1a-ba0729dfd525)
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/75314095/d108d5c2-6a61-4b7b-98ae-d6e5ea1b8a69)
![image](https://github.com/jomjol/AI-on-the-edge-device/assets/75314095/74564623-41b9-4686-b679-184689017c85)

**Comment by ghost** [comment]
Du hast die ROIs zu eng um die Ziffern gerahmt. Schau dir noch mal die Doku dazu an https://jomjol.github.io/AI-on-the-edge-device-docs/ROI-Configuration/

Die ROIs dürfen sich überlappen.

**Reply by timostr** [reply]
Das ein Fehler gemeldet wird (negativ value) könnte auch daran liegen, dass Du folgende Werte gemessen bzw. konfiguriert hast:
1. old = 8.440
2. new = 9.515
3. Maximum rate value = 0.3
4. Maximum rate type = RateChange 

D.h. pro Minute darf es nur eine Änderung kleiner als 0.3 qm geben. Rechnung (9,515 - 8,440) / 0,3 = 3,583 Minuten.
Falls Du häufiger als 3,584 Minuten eine neue Ablesung machst, dann gibt es bei deinem Setup einen Fehler.

Allerdings wird es sehr schwer mehr als 300 Liter pro Minute im Haus zu verbrauchen. :-)

**Reply by SybexX** [reply]
@timostr du meinst eher "Status: Rate too high"

"Neg. Rate - Read" würde nur bei der folgenden Konstellation auftreten:
old = 9.515
new = 8.440

**Comment by tschuster89** [comment]
Wie hast du das mit dem "Starten" des Zählers gelöst? Das Display geht ja nach kurzer Zeit aus. Ich hatte auch schon überlegt einfach ein Bild zu machen und die Digits zu lesen. Wäre nett wenn du kurz Rückmeldung zur Umsetzung geben könntest. 

Beste Grüße
Tim

**Reply by Henry-Sir** [reply]
Hi,

sry für die verspätete Antwort.
Eigentlich habe ich gar nicht gemacht, Habe die ganze Installation, die vorher auf dem Analogzähler lief, so genommen und auf den Digitalzähler "geklebt".

Ja das Display geht immer wieder automatisch aus, der hat aber ein Lichtsensor drin und dann geht das Display wieder an. Durch den Blitz geht das Display also immer wieder an.
Aber aufpassen, dass der Zeitabstand nicht zu gering ist. Wenn das Display noch nicht ausgegangen ist, wechselt die Anzeige und du hast die Zählerstande nicht mehr.





Zur "Installation", ich habe das Ganze mit einem HT Rohr umgesetzt:

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/75314095/1f02cb9e-1f19-4f13-acae-716d6fa44387)



Zu meinem Problem, ich habe es leider noch nicht ganz in Griff bekommen, habe schon viel mit den Einstellung bzw. setzen der Digit ROI's probiert. 
Ich habe mir dazu eine einfache Abhilfe geschaffen. Ich setze die Werte jetzt automatisch wieder richtig, wenn über 1 Stunde die Werte auseinanderlaufen (Homeassistant Automatisierung und Script eingerichtet). Hat halt manchmal den Nachteil, dass falsche Werte (zu Hohe) für einen längeren Zeitraum anstehen. Aber das wird dann auch noch verbraucht, dass das wieder passt :)

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/75314095/01958225-289b-4bd4-90e8-07f2c8abd687)

![image](https://github.com/jomjol/AI-on-the-edge-device/assets/75314095/c5022124-8ac5-4afc-b69b-5bc2042deefd)



Automatisierung:
```

alias: Wasserzähler Alarm set Pre Value
description: |-
  URL für Pre Value setzen:

  http://192.168.189.151/setPreValue?value=17.324&numbers=main
trigger:
  - platform: numeric_state
    entity_id: sensor.watermeter_raw
    for:
      hours: 1
      minutes: 0
      seconds: 0
    value_template: >-
      {{ ((( state.state | float ) -
      (states('sensor.meter_water_zahlerstand_bezug') | float))  * 1000 ) |
      round(0) }}
    above: 10
    enabled: true
  - platform: template
    value_template: |-
      {% if ((((states('sensor.watermeter_raw')| float ) -
       (states('sensor.meter_water_zahlerstand_bezug') | float))  * 1000 ) |
       round(0)) > 100 %}
      true {% else %} false {% endif %}
    alias: " When Raw Value is above 100 for 1:00:00"
    for:
      hours: 1
      minutes: 0
      seconds: 0
condition: []
action:
  - service: script.wasserzaehler_set_pre_value
    data: {}
    enabled: true
mode: single
```

Script (Kann man auch in die Automatisierung mit einbauen, ich habe es getrennt)


```
alias: Wasserzähler set Pre Value
sequence:
  - type: turn_off
    device_id: 37f5e888eaf8383247d59dc1bbaf01e5
    domain: switch
    entity_id: sensor.meter_water_zahlerstand_bezug
    enabled: false
    alias: Wasserzähler Zuordnung
  - service: rest_command.watermeter_setprevalue
    data:
      ip: "{{ states('sensor.watermeter_ip')| string }}"
      number: "{{ states('sensor.watermeter_raw')| string }}"
    enabled: true
mode: single
```
