### DISCUSSION TITLE
Can I trigger "set previous value" remotely?

### DISCUSSION THREAD

**Discussion by swa72** [jomjol/AI-on-the-edge-device#2546] [Q&A]
I have integrated the device into Home Assistant and it works ok. Some days I get little to no errors. On other days, a problem persists for hours. 

I don't mind having negative reads in the energy dashboard as they level out at least on the weekly level.

So the idea is basically: if a problem persists for more than, say, 4 hours. simply set the previous value to whatever you read now.

Is there such an option? I reckon https://jomjol.github.io/AI-on-the-edge-device-docs/MQTT-API/ describes a way, but I am not sure.

**Comment by caco3** [comment]
Did you try https://jomjol.github.io/AI-on-the-edge-device-docs/MQTT-API/#ctrlset_prevalue-be-aware-this-feature-is-not-available-for-versions-1511-and-older ?

Alternatively, REST will work: https://jomjol.github.io/AI-on-the-edge-device-docs/REST-API/#setprevalue

**Comment by swa72** [comment]
Thanks for the hint, I've reflected that in the following automation. 

The automation is triggered, if there is a problem for more than 1,5h.

If the problem is related to a negative read, set the previous value again and notify me. If not, just notify me.

```
alias: Notify of meter problem
description: ""
trigger:
  - platform: state
    entity_id:
      - binary_sensor.watermain_problem
    from: null
    to: "on"
    for:
      hours: 1
      minutes: 30
      seconds: 0
condition: []
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ states('sensor.watermain_error') is search('Neg. Rate') }}"
        sequence:
          - service: notify.mobile_app_iphone
            data:
              title: Warning
              message: >-
                {{ trigger.entity_id }} has negative read problem: {{
                states('sensor.watermain_error') }}
          - service: mqtt.publish
            data:
              topic: watermain/ctrl/set_prevalue
              payload: "{\"numbersname\": \"main\", \"value\": -1}"
    default:
      - service: notify.mobile_app_iphone
        data:
          title: Warning
          message: >-
            {{ trigger.entity_id }} has other meter problem: {{
            states('sensor.watermain_error') }}
mode: single
```
