### DISCUSSION TITLE
Homeassistant - sometimes 0 m³ and always gaps in the graphics.

### DISCUSSION THREAD

**Discussion by Mkay505** [jomjol/AI-on-the-edge-device#760] [Q&A]
First of all - great project.

I have a problem with the display of the water meter value in Homeassistant.
Sometimes the value is given as 0 m³, sometimes the right value is present.
As a result, the graphics have gaps.
Can I fix the fact that it always shows the last value and the graphic curve is continuous in Homeassistant?

![image](https://user-images.githubusercontent.com/75015019/162143632-fa74cc3c-b43e-495a-afb3-365fec6678f3.png)
![image](https://user-images.githubusercontent.com/75015019/162143861-8fb451c0-ffdb-4f89-94b8-fe7960e06b8d.png)

My code in a "sensor" folder as "wasserzahler.yaml":

- platform: mqtt    #Minus instead of point!

    name: "Wasserzähler"
    state_topic: wasserzaehler/main/json
    value_template: "{{ value_json.value }}"
    unit_of_measurement: "m3"
    icon: "mdi:water"

**Comment by jomjol** [comment]
If there is a false value, this is not transfered. You need to make a filter on the receiver side if you want to remove those inputs.

**Comment by NitramH** [comment]
Hi,

does anyone has a proposal for such a filter?
Sorry, but I'm not yet so skilled in programming Homeassistant

**Reply by rspring** [reply]
I had the exact same issue. Now I simply use the Home Assistant outlier filter, which works great for me:
```yaml
rest:
  - resource: http://192.168.1.51/wasserzaehler.html
    scan_interval: 300
    sensor:
      - name: Water Consumption (L)
        unique_id: water_consumption_l
        unit_of_measurement: 'l'
        icon: mdi:water-circle

sensor:
  - platform: filter
    name: Water Consumption (L) Filtered
    unique_id: water_consumption_l_f
    entity_id: sensor.water_consumption_l
    filters:
      - filter: outlier
        window_size: 4
        radius: 200
```

**Comment by lal12** [comment]
I am using the JSON API with the following code:

```yaml
  - platform: rest
    resource: http://gasmeter.fritz.box/json
    name: "Gaszähler"
    unit_of_measurement: "m³"
    device_class: "gas"
    icon: "mdi:meter-gas"
    value_template: "{{ float(value_json.main.value) }}"
    json_attributes_path: "$.main"
    unique_id: "gasmeter"
    state_class: "total_increasing"
```

I think generally the JSON api is a bit more safe to use, though unfortunately sometimes I have errors with that too. I didn't quite got to the bottom of it.

**Comment by DanielWe2** [comment]
You could try to use the Filter sensor using your MQTT sensor as the base: https://www.home-assistant.io/integrations/filter/    with the setting "range" and a lower_bound of your current value. That way it should filter out the 0 values.

**Reply by caco3** [reply]
Maybe the `JSON` MQTT topic gets sent after every run?
I use the `value` topic and I dont see gabs in Homassistant.

Here my config:
```
- platform: mqtt
  state_topic: "wasserzaehler/main/value"
  name:  "Wasserzähler"
  unique_id: Wasserzaehler
  state_class: measurement
  device_class: gas
  unit_of_measurement: "m³"

- platform: mqtt
  state_topic: "wasserzaehler/main/raw"
  name: "Wasserzähler_raw"
  unique_id: Wasserzaehler_raw
  state_class: measurement
  device_class: gas
  unit_of_measurement: "m³"

- platform: mqtt
  state_topic: "wasserzaehler/uptime"
  name: "Wasserzähler Uptime"
  unique_id: Wasserzaehler_uptime
  state_class: measurement
  device_class: duration
  unit_of_measurement: "s"
```

![grafik](https://user-images.githubusercontent.com/1783586/193143107-8d957286-3607-47b3-af69-f8cce346268a.png)

**Comment by faberlau** [comment]
Hello together, I'm using this configuration for 'homeassistant' and it works fine:

```
mqtt:
  sensor:
    - object_id: "energy_total"
      unique_id: "energy001"
      name: "Strom Verbrauch"
      state_topic: "stromzaehler/number1/value"
      state_class: total_increasing
      device_class: energy
      value_template: "{{ value }}"
      unit_of_measurement: "kWh"
      availability:
        - topic: "stromzaehler/number1/error"
          payload_available: "no error"
          payload_not_available: "error"
      icon: "mdi:flash"
     
    - object_id: "energy_rate"
      unique_id: "energy002"
      name: "Strom Leistung"
      state_topic: "stromzaehler/number1/rate"
      value_template: "{{ value }}"
      unit_of_measurement: "W"
      icon: "mdi:swap-vertical"
     
    - object_id: "energy_timestamp"
      name: "Strom Erfassungszeitpunkt"
      unique_id: "energy003"
      state_topic: "stromzaehler/number1/timestamp"
      value_template: "{{ value }}"
      icon: "mdi:clock-outline"
 
    - object_id: "energy_rssi" 
      name: "Strom WLAN-RSSI"
      unique_id: "energy004"
      state_topic: "stromzaehler/wifiRSSI"
      value_template: "{{ value }}" 
      unit_of_measurement: "dBm"
      icon: "mdi:rss"
      
    - object_id: "gas_total"
      unique_id: "gas001"
      name: "Gas Verbrauch"
      state_topic: "gaszaehler/number1/value"
      state_class: total_increasing
      device_class: gas
      value_template: "{{ value }}"
      unit_of_measurement: "m³"
      availability:
        - topic: "gaszaehler/number1/error"
          payload_available: "no error"
          payload_not_available: "error"
      icon: "mdi:fire"
     
    - object_id: "gas_rate"
      unique_id: "gas002"
      name: "Gas Verbrauch/Zeit"
      state_topic: "gaszaehler/number1/rate"
      value_template: "{{ value }}"
      icon: "mdi:swap-vertical"
     
    - object_id: "gas_timestamp"
      unique_id: "gas003"
      name: "Gas Erfassungszeitpunkt"
      state_topic: "gaszaehler/number1/timestamp"
      value_template: "{{ value }}"
      icon: "mdi:clock-outline"
     
    - object_id: "gas_rssi" 
      name: "Gas WLAN-RSSI"
      unique_id: "gas004"
      state_topic: "gaszaehler/wifiRSSI"
      value_template: "{{ value }}" 
      unit_of_measurement: "dBm"
      icon: "mdi:rss"
```
