### ISSUE TITLE
Improve Homeassistant wiki page

### ISSUE THREAD

**Issue by caco3** [jomjol/AI-on-the-edge-device#1108]
https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistant

https://github.com/jomjol/AI-on-the-edge-device/discussions/760

**Comment by caco3** [comment]
I am currently working how to use it properly, will update the wiki page once I have a better understanding

**Comment by dcboy87** [comment]
Unfortunately Homeassistant throws a warning when using your configuration:
https://www.home-assistant.io/integrations/sensor.mqtt/#new_format

![grafik](https://user-images.githubusercontent.com/45015463/194095331-830f2dc2-766b-43a9-aab1-45135f44893b.png)


Maybe it would be helpful to implement the HA device discovery?

**Comment by caco3** [comment]
> Unfortunately Homeassistant throws a warning when using your configuration: https://www.home-assistant.io/integrations/sensor.mqtt/#new_format
> 
> ![grafik](https://user-images.githubusercontent.com/45015463/194095331-830f2dc2-766b-43a9-aab1-45135f44893b.png)
> 
> Maybe it would be helpful to implement the HA device discovery?
> 
> This was working for me, maybe it needs to be adjusted:
> 
> ```
> alias: MQTT-SmartMeterWater_Device-Publish
> sequence:
>   - service: mqtt.publish
>     data:
>       topic: homeassistant/sensor/watermeter_total/total/config
>       retain: true
>       payload: |-
>         {
>           "~": "wasserzaehler",
>           "name": "Zählerstand total",
>           "unit_of_meas": "m³",
>           "icon": "mdi:water",
>           "state_topic": "~/main/json",
>           "value_template": "{{ '{{ value_json.value }}' }}",
>           "json_attributes_topic": "~/main/json",
>           "unique_id": "smartmeter.watertotal.total",
>           "availability_topic": "~/connection",
>           "payload_available": "connected",
>           "payload_not_available": "connection lost",
>           "device": {
>             "configuration_url": "http://192.168.178.145",
>             "identifiers": ["34945423E484"],
>             "name": "ha.Wasseruhr",
>             "model": "PTB004",
>             "manufacturer": "Sensus"
>           }
>         }
>   - service: mqtt.publish
>     data:
>       topic: homeassistant/sensor/watermeter_total/rate/config
>       retain: true
>       payload: |-
>         {
>           "~": "wasserzaehler",
>           "name": "Verbrauch",
>           "unit_of_meas": "m³",
>           "icon": "mdi:swap-vertical",
>           "state_topic": "~/main/json",
>           "value_template": "{{ '{{ value_json.rate }}' }}",
>           "json_attributes_topic": "~/main/json",
>           "unique_id": "smartmeter.watertotal.rate",
>           "availability_topic": "~/connection",
>           "payload_available": "connected",
>           "payload_not_available": "connection lost",
>           "device": {
>             "identifiers": ["34945423E484"],
>             "name": "ha.Wasseruhr",
>             "model": "PTB004",
>             "manufacturer": "Sensus"
>           }
>         }
> mode: single
> ```
> 
> this comes from my HA, with help from [#299 (comment)](https://github.com/jomjol/AI-on-the-edge-device/issues/299#issuecomment-993448517)

hmm, are you using a release from the future?
I am also on the latest docker container but am on `2022.6.5`!

I will have a look and update the wiki, but it will take a while, will be on holiday and busy in the next weeks.

```
alias: MQTT-SmartMeterWater_Device-Publish
sequence:
  - service: mqtt.publish
```

That's all about publishing from HA side. There is no need for it to use the ESP as a sensor!

**Comment by dcboy87** [comment]
Yes, i'm using the latest HA version (2022.9.6)

I am receiving the MQTT message in HA, then create a new MQTT message formed like a HA device discovery message with data from the watermeter message. Thats my script in HA.;-)

**Comment by dcboy87** [comment]
and this is my updated configuration.yaml with your template from the wiki:

````
mqtt:
  sensor:
    - state_topic: "wasserzaehler/main/value"
      name: "Watermeter Value"
      unique_id: watermeter_value
      unit_of_measurement: 'm³'
      state_class: total_increasing
      device_class: gas # There is no class for water, use 'gas' instead
      icon: 'mdi:water'

    - state_topic: "wasserzaehler/main/rate"
      name: "Watermeter Rate"
      unique_id: watermeter_rate
      unit_of_measurement: 'm³'
      state_class: measurement
      device_class: gas # There is no class for water, use 'gas' instead
      icon: 'mdi:water'

    - state_topic: "wasserzaehler/uptime"
      name: "Watermeter Uptime"
      unique_id: watermeter_uptime
      unit_of_measurement: 's'
      state_class: measurement
      device_class: duration
````
