### ISSUE TITLE
Prometheus exporter

### ISSUE THREAD

**Issue by maticslaszlo** [jomjol/AI-on-the-edge-device#1345]
### The Feature

Hello

It would be great, if it's possible to have a prometheus exporter on /metrics url, with similar data as in MQTT messages

Regards
Laszlo

**Comment by maticslaszlo** [comment]
What kind of documentation do you think? Doc about writing prometheus exporter, or something else?

I think just print out in prometheus style same, as to MQTT
for example:
`# HELP meter_counter Counter 
# TYPE meter_counter counter
meter_counter{device="inside",metertype="watermeter"} 46.84249

# HELP meter_counter_error
meter_counter_error{device="inside",metertype="watermeter"} 1

# HELP meter_counter_raw Counter reading raw data
# TYPE meter_counter_raw counter
meter_counter_raw{device="inside",metertype="watermeter"} 46.82912
# HELP meter_timestamp Counter timestamp
meter_timestamp{device="inside",metertype="watermeter"} 1668981165
`
I've produce this from MQTT data, but it's quite difficult way

docs: https://prometheus.io/docs/instrumenting/writing_exporters/

Regards
Laszlo

**Comment by caco3** [comment]
I needed quite some time to get Homeassistant MQTT Discovery working.
But I do not have time to do the same for Prometheus. If anybody else wants to do it, just go ahead and create a Pull Request. But I am not able to invest time into it, sry.

**Comment by hansmi** [comment]
I had a need to track metrics from multiple AI-on-the-edge devices in Prometheus. @schluo wrote [`schluo/gasmeter-exporter`](https://github.com/schluo/gasmeter-exporter) (see discussion #1260). That was too specific for my needs, so I wrote the more generic [`prometheus-ai-on-the-edge-device-exporter`](https://github.com/hansmi/prometheus-ai-on-the-edge-device-exporter/) which retrieves information via the [REST API](https://jomjol.github.io/AI-on-the-edge-device-docs/REST-API/).

The exporter is available as source, binaries as well as a Docker image (instructions copied from [`README.md`](https://github.com/hansmi/prometheus-ai-on-the-edge-device-exporter/blob/main/README.md) as the authoritative source):

```shell
docker run --rm -p 8081:8081 ghcr.io/hansmi/prometheus-ai-on-the-edge-device-exporter:latest
```

The Prometheus scrape config example uses the target address for the `target` parameter to the `/probe` URL endpoint:

```yaml
- job_name: ai-on-the-edge-device
  metrics_path: /probe
  static_configs:
    - targets:
      - http://water
      - http://gas
  relabel_configs:
    - source_labels: [__address__]
      target_label: __param_target
    - source_labels: [__param_target]
      target_label: instance
    - target_label: __address__
      replacement: "exporter:8081"
```

Example metrics:

```shell
$ curl http://localhost:8081/probe?target=http://water
…
ai_on_the_edge_device_cpu_temperature_celsius 46
ai_on_the_edge_device_flow_value{name="main"} 12.345
…
```
