### ISSUE TITLE
HASS MQTT Discovery Timestamp Sensor with correct Timestamp Device Class

### ISSUE THREAD

**Issue by Gloomyeye** [jomjol/AI-on-the-edge-device#1428]
### The Feature

Hello,

after updating to the lastest version, I activated the Home Assistant MQTT Discovery service. The timestamp sensor shows the value "2022-11-29T06:23:50". My manual added mqtt sensor has the device_class _timestamp_. Here is the code:

```
sensor:
  - name: "Wasserzähler Zeitstempel"
    object_id: hwr_sensor_watermeter_timestamp
    unique_id: hwr_sensor_watermeter_timestamp
    state_topic: "watermeter/main/timestamp"
    device_class: timestamp
    value_template: "{{ value }}+0200"
    icon: "mdi:clock-outline"
    entity_category: diagnostic
```

It would be great if the timestamp sensor of the HASS MQTT discovery service could also send values with the device class timestamp. The timezone needs to be included to the current return value.
