### ISSUE TITLE
Can you make auto reboot sheulder?

### ISSUE THREAD

**Issue by lynxchat4** [jomjol/AI-on-the-edge-device#1794]
### The Feature

Hello!
Can you make auto reboot sheulder?
After 1 week working can be stop to send MQTT data and no log data.  In web all working normaly.
version Release: v13.0.7 (Commit: 304b9e0)
After reboot - work normaly.

**Comment by caco3** [comment]
what means `sheulder`?

And please provide a logfile

**Comment by lynxchat4** [comment]
> what means `sheulder`?
> 
> And please provide a logfile

Sorry. I meant: " schedule"

Now all work fine.
LOG Data Viewer - is normal.

LOG "Log Viewer" files are missing after the problem started. Now put DEBUG

**Comment by caco3** [comment]
Why do you want to periodically reboot it?
Unless there are random crashes as some people experience, it runs stable over days..weeks..!

Eg. my 2 devices are now running since > 7 resp. 8 days.

**Comment by lynxchat4** [comment]
7-8 days works for me too. But already 2 times it stops sending data and has to be rebooted manually. Everything is recognized and logged, but not sent by MQTT. I would like it to work 24/7 365 days a year, without human intervention.

**Comment by caco3** [comment]
That seems to be a bug, please provide the logfiles with DEBUG level so we can try to understand and fix it!

**Comment by lynxchat4** [comment]
Yes, I changed the settings. As soon as there is an error, I will write here

**Comment by nliaudat** [comment]
Perhaps the idea is not bad to add an option to reboot after X rounds (a round is defined by auto timer Interval) and stored in memory 
(sorry, I have no access to the source code actually to give you the variable, that should be in classflow...)

**Comment by alfista2600** [comment]
mine stopped responding or reporting but still responded to pings. It was over the holidays and I was too busy to notice. Would love to be able to send a reboot command via MQTT... not sure what the issue was...

**Comment by caco3** [comment]
I had this issue before, ping still working but UI not. But I never had it when I was debugging.
And I am not sure if a reboot over MQTT still would work. In your case, did the device still send messages over MQTT when the UI was dead?

**Comment by nliaudat** [comment]
reboot after X rounds is the best way to go. 
Can be disabled or set very high (1y)

Every onboard chips needs to be rebooted at intervall.

**Comment by caco3** [comment]
> Every onboard chips needs to be rebooted at intervall.

Duuh, only if you don't do a proper design! The customers of my company would not accept this... :smiley_cat:

**Comment by b2un0** [comment]
for me, i resolved this issue within Home Assistant and a [rest_command](https://www.home-assistant.io/integrations/rest_command/)

`configuration.yaml`

```yaml
rest_command:
  gasmeter_reboot:
    url: http://192.168.155.52/reboot
  watermeter_reboot:
    url: http://192.168.155.51/reboot
```

`automation.yaml`

```yaml
alias: System - Watermeter / Gasmeter reboot
trigger:
  - platform: time
    at: "03:00:00"
action:
  - service: rest_command.gasmeter_reboot
  - service: rest_command.watermeter_reboot
mode: single
```

in my case it relates to

and
https://github.com/jomjol/AI-on-the-edge-device/discussions/2193
https://github.com/jomjol/AI-on-the-edge-device/discussions/2425
