### ISSUE TITLE
Konfigurierbarer LWT Payload

### ISSUE THREAD

**Issue by syssi** [jomjol/AI-on-the-edge-device#195]
Vielen Dank für das super Projekt! Hier ist es seit heute in Betrieb und an Home Assistant angebunden. Toll waere, wenn ich die Erreichbarkeit des Geraetes sauber monitoren koennte. Mir ist jedoch nicht ganz klar, welche Meldungen alles auf dem Topic "error" erscheinen koennen. Am liebsten waere mit ein separates Topic (LWT?) für den letzten Willen, auf welchem entweder "online" oder der letzte Wille "offline" zu hoeren ist.

Ich habe versucht "connection lost" als Alternative für "offline" zu nutzen, nur leider kommt Home Assistant nicht mit dem Wert "null" für "online" klar.

![esp32-watermeter](https://user-images.githubusercontent.com/2735933/115970192-34aad400-a541-11eb-8ac4-cfeb724b8db5.jpg)

**Comment by jomjol** [comment]
Hi, 
danke für deinen Input. Ich würde eigentlich ungerne noch eine weitere LWT einführen. Eventuell könnte ich statt einer "NULL" eine leeren String in Form eines Blank-Zeichens schicken. Würde das helfen?

**Comment by syssi** [comment]
Das würde mir bereits helfen. Den Online- und Offline-Payload konfigurierbar machen wäre auch eine Hilfe. Alle Werte darüberhinaus würde ich dann einfach ignorieren.

**Comment by jomjol** [comment]
Inzwischen im Release implementiert - hoffe es funktioniert. Wenn nicht, bitte Issue einfach nochmal öffnen.

**Comment by syssi** [comment]
Macht was es soll. Vielen Dank! Meine Home Assistant Konfiguration fuer die Nachwelt:

```
binary_sensor:
  - platform: mqtt
    name: "basment watermeter lwt"
    state_topic: "watermeter/error"
    payload_on: " "
    payload_off: "connection lost"
    device_class: connectivity

sensor:
  - platform: mqtt
    unique_id: "basement watermeter reading"
    name: "basement watermeter reading"
    state_topic: "watermeter/reading"
    value_template: "{{ value }}"
    unit_of_measurement: "qm"
    icon: mdi:water
    availability_topic: "watermeter/error"
    payload_available: " "
    payload_not_available: "connection lost
```
