### ISSUE TITLE
Home Assistant sensor yaml

### ISSUE THREAD

**Issue by deadly667** [jomjol/AI-on-the-edge-device#299]
Hi,
first of all, great project and kudos!

I wanted to add documentation for adding Mqtt fields into Home Assistant. Unfortunately as I cannot pull request Wiki I will add here:

To add Mqtt fields to Home Assistant you have to add those into your `configuration.yaml`. I use this project for electricity meter there for I put `unit_of_measurement` "kWh". Don't forget to update your Mqtt topic instead of mines `powermeter`. In the same way you can add others if you use multiple rows reading. 

 ```
sensor:
  - platform: "mqtt"
    name: "Main meter AIOE"
    state_topic: "powermeter/main/value"
    value_template: "{{ value }}"
    unit_of_measurement: "kWh"
    icon: "mdi:flash"
  - platform: "mqtt"
    name: "Main rate meter AIOE"
    state_topic: "powermeter/main/rate"
    value_template: "{{ value }}"
    icon: "mdi:swap-vertical"
  - platform: "mqtt"
    name: "Main timestamp meter AIOE"
    state_topic: "powermeter/main/timestamp"
    value_template: "{{ value }}"
    icon: "mdi:clock-outline"
binary_sensor:
  - platform: "mqtt"
    name: "Main error meter AIOE"
    state_topic: "powermeter/main/error"
    value_template: "{{ value != 'no error' }}"
    json_attributes_topic: "powermeter/main/json"
    icon: "mdi:alert-circle"
 ```

**Comment by Mogwaiz** [comment]
Thanks, this helped me alot!

**Comment by jomjol** [comment]
Thanks a lot - I have integrated it into the wiki: https://github.com/jomjol/AI-on-the-edge-device/wiki/Integration-Home-Assistent

**Comment by Henry-Sir** [comment]
> ```
> binary_sensor:
>  - platform: "mqtt"
>    name: "Main error meter AIOE"
>    state_topic: "powermeter/main/error"
>    value_template: "{{ value != 'no error' }}"
>    json_attributes_topic: "powermeter/main/json"
>    icon: "mdi:alert-circle"
> ```

Hi, 

the binary_sensor did not work for me and so I adjusted it.
Source: https://community.home-assistant.io/t/binary-sensor-mqtt-with-json/147619/7

```
value_template: "{{ 'OFF' if 'no error' in value else 'ON'}}" 
```


I publish the sensors via MQTT and thereby attached to a device.
The whole set up as a script and an automation that starts the script when Home Assistant is started.

Don't forget to update your mqtt topic in "~". 
For the device ID take a uniqe number, not "12345678".
(The topic under "topic" is the configuration topic for Home Assitant. https://www.home-assistant.io/docs/mqtt/discovery/ )

### script
```
alias: MQTT-SmartMeterWater_Device-Publish
sequence:
  - service: mqtt.publish
    data:
      topic: homeassistant/sensor/watermeter_total/total/config
      retain: true
      payload: |-
        {
          "~": "watermeter",
          "name": "Meter-Water - Counter",
          "unit_of_meas": "m³",
          "icon": "mdi:water",
          "state_topic": "~/main/json",
          "value_template": "{{ '{{ value_json.value}}' }}",
          "json_attributes_topic": "~/main/json",
          "unique_id": "smartmeter.watertotal.total",
          "availability_topic": "~/connection",
          "payload_not_available": "connection lost",
          "device": {
            "identifiers": ["12345678"],
            "name": "Total water meter",
            "model": "M100",
            "manufacturer": "aquamess"
          }
        }
  - service: mqtt.publish
    data:
      topic: homeassistant/sensor/watermeter_total/rate/config
      retain: true
      payload: |-
        {
          "~": "watermeter",
          "name": "Meter-Water - Rate",
          "unit_of_meas": "m³",
          "icon": "mdi:swap-vertical",
          "state_topic": "~/main/json",
          "value_template": "{{ '{{ value_json.rate}}' }}",
          "json_attributes_topic": "~/main/json",
          "unique_id": "smartmeter.watertotal.rate",
          "availability_topic": "~/connection",
          "payload_available": "connected",
          "payload_not_available": "connection lost",
          "device": {
            "identifiers": ["12345678"],
            "name": "Total water meter",
            "model": "M100",
            "manufacturer": "aquamess"
          }
        }
  - service: mqtt.publish
    data:
      topic: homeassistant/binary_sensor/watermeter_total_error/config
      retain: true
      payload: |-
        {
          "~": "watermeter",
          "name": "Meter-Water - Alert",
          "icon": "mdi:alert",
          "state_topic": "~/main/error",
          "value_template": "{{ "{{ 'OFF' if 'no error' in value else 'ON'}}" }}",
          "json_attributes_topic": "~/main/json",
          "unique_id": "smartmeter.watertotal.error",
          "availability_topic": "~/connection",
          "payload_available": "connected",
          "payload_not_available": "connection lost",
          "device": {
            "identifiers": ["12345678"],
            "name": "Total water meter",
            "model": "M100",
            "manufacturer": "aquamess"
          }
        }
mode: single
```

### automation
```
alias: MQTT-Devices-Publish
description: ''
trigger:
  - platform: homeassistant
    event: start
condition: []
action:
  - service: script.mqtt_smartmeterwater_device_publish
mode: single
```
