### ISSUE TITLE
Add Output to use HA Consumptiom Board

### ISSUE THREAD

**Issue by hermann1514** [jomjol/AI-on-the-edge-device#333]
Hi,
HomeAssistant has now a new Engergy Dashboard. 
The Sensors must have some Outputs, so the HA Energy Modul can use it.

Is it possible to add the wanted output to MQTT?
https://developers.home-assistant.io/docs/core/entity/sensor#long-term-statistics

Thx.
Regards
Hermann

**Comment by jomjol** [comment]
Hello Hermann,
are you sure, that the parameter details like "state_class" needs to be set in the MQTT-client side or is it some settings in the HA itself? I don't use HA, so I don't know something about the system or setting. Maybe you can clarify this?

Currently don't know, how to set it in my system. Currently I'm working on other features. But I can leave this issue open for some time until you have clarified, what exactly needs to be set in the MQTT client.

Best regards,
  jomjol

**Comment by pixeldoc2000** [comment]
@hermann1514 You are talking about the HA **Energy** Dashboard. Please change the Issue from "Consumptiom Board" to "Energy Dashboard", so others can find it more easily ;-)

This is my configuration.yaml entry for my Grind Energy Meter:
```
sensor:
  - platform: mqtt
    state_topic: "powermeter/main/value"
    name: "Powermeter"
    icon: mdi:transmission-tower
    unit_of_measurement: kWh
    state_class: measurement
    device_class: energy
    availability_topic: "powermeter/connection"
    payload_available: "connected"
    payload_not_available: "connection lost"
    json_attributes_topic: "powermeter/main/json"
    unique_id: x762066429104a7492d3b7c8ddbe6fas
```
customize.yaml
```
sensor.powermeter:
  last_reset: '1970-01-01T00:00:00+00:00'
```
![grafik](https://user-images.githubusercontent.com/376715/133515393-d3fea7db-0a39-4fef-9f8d-c074c8b87209.png)
